train:
  batch_size: 2
  val_batch_size: 2
  learning_rate: 0.0001
  weight_decay: 0.01
  epochs: 100
  gradient_clip_val: 1.0
  accumulate_grad_batches: 2
  devices: 8
  num_nodes: 1
  accelerator: gpu
  strategy: ddp
  precision: 32

data:
  data_path: ./data/
  train_years: [2013, 2014, 2015, 2016]
  val_years: [2017]
  test_years: [2018]
  variables:
    - u
    - v
    - temp
    - rh
    - psfc
    - pm10
    - so2
    - no2
    - co
    - o3
    - lat2d
    - lon2d
    - pm25
    - elevation
    - population
  target_variables:
    - pm25
    - pm10
    - so2
    - no2
    - co
    - o3
  forecast_hours: [12, 24, 48, 96]
  time_step: 1
  normalize: true
  target_resolution: [128, 256]
  num_workers: 4

model:
  img_size: [128, 256]
  patch_size: 2
  embed_dim: 768
  depth: 6
  decoder_depth: 2
  num_heads: 8
  mlp_ratio: 4
  drop_path: 0.1
  drop_rate: 0.1
  parallel_patch_embed: true
  use_physics_mask: true

callbacks:
  early_stopping:
    monitor: val_loss
    patience: 10
    mode: min
  model_checkpoint:
    monitor: val_loss
    mode: min
    save_top_k: 3
